name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: garronej/covid19-dashboard:master 
          build-args: |
            "AWS_S3_ENDPOINT=${{ secrets.AWS_S3_ENDPOINT }}"
            "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}"
            "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"

  